Add warning for detect lifecycle.
As part of mutli-buildpack solution, this cannot be used in the
detect phase of the lifecycle, force exit.

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,1 +1,7 @@
 #!/usr/bin/env bash
+#!/usr/bin/env bash
+
+echo "-----> VulsBuildpack/detect"
+echo "       \033[0;31mATTENTION: Cannot use as final buildpack, exiting.\e[0m"
+
+exit 1
